#!/bin/sh

case "$1" in
	*.extension) extension-handler "$1";;
	*.xls) xls2csv "$1" ;;
	*.kmz) unzip -p "$1" ;;
	*.pex) unzip -p "$1" ;;
	*)
		# We don't handle this format.
		exit 1
esac

# No further processing by lesspipe necessary
exit 0

